FROM owasp/dependency-check:{{ versions.dependencyCheck }}

USER root
RUN chown -R dependencycheck:dependencycheck /usr/share/dependency-check /report

USER dependencycheck

VOLUME /usr/share/dependency-check/data
